CRITICAL - 2023-10-13 00:14:31 --> Call to undefined function ()
in APPPATH\Controllers\User.php on line 23.
 1 APPPATH\Controllers\User.php(14): App\Controllers\User->genericResponse('', [...], '', 200)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 00:31:51 --> Undefined variable $users
in APPPATH\Views\users.php on line 56.
 1 APPPATH\Views\users.php(56): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $users', 'C:\\teste_api_codeigniter\\app\\Views\\users.php', 56)
 2 SYSTEMPATH\View\View.php(226): include('C:\\teste_api_codeigniter\\app\\Views\\users.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('users', [], true)
 5 APPPATH\Controllers\User.php(15): view('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 00:33:20 --> CodeIgniter\Router\RouteCollection::processArrayCallableSyntax(): Return value must be of type string, array returned
in SYSTEMPATH\Router\RouteCollection.php on line 1553.
 1 SYSTEMPATH\Router\RouteCollection.php(1417): CodeIgniter\Router\RouteCollection->processArrayCallableSyntax('user', [...])
 2 SYSTEMPATH\Router\RouteCollection.php(1013): CodeIgniter\Router\RouteCollection->create('get', 'user', [...], null)
 3 APPPATH\Config\Routes.php(10): CodeIgniter\Router\RouteCollection->get('user', [...])
 4 SYSTEMPATH\Router\RouteCollection.php(339): require('C:\\teste_api_codeigniter\\app\\Config\\Routes.php')
 5 SYSTEMPATH\CodeIgniter.php(787): CodeIgniter\Router\RouteCollection->loadRoutes()
 6 SYSTEMPATH\CodeIgniter.php(442): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 00:36:45 --> Call to a member function paginate() on array
in APPPATH\Controllers\User.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 00:37:12 --> Call to a member function findAll() on array
in APPPATH\Controllers\User.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 15:00:41 --> Declaration of App\Controllers\User::create(App\Controllers\Request $request) must be compatible with CodeIgniter\RESTful\ResourceController::create()
in APPPATH\Controllers\User.php on line 17.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 15:01:18 --> Declaration of App\Controllers\User::delete() must be compatible with CodeIgniter\RESTful\ResourceController::delete($id = null)
in APPPATH\Controllers\User.php on line 36.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 15:01:24 --> Declaration of App\Controllers\User::delete() must be compatible with CodeIgniter\RESTful\ResourceController::delete($id = null)
in APPPATH\Controllers\User.php on line 36.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 15:01:26 --> Declaration of App\Controllers\User::delete() must be compatible with CodeIgniter\RESTful\ResourceController::delete($id = null)
in APPPATH\Controllers\User.php on line 36.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 15:02:33 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 20.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 15:06:28 --> Class "App\Controllers\UserModel" not found
in APPPATH\Controllers\User.php on line 20.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 15:07:55 --> Undefined property: App\Controllers\User::$rquest
in APPPATH\Controllers\User.php on line 22.
 1 APPPATH\Controllers\User.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\User::$rquest', 'C:\\teste_api_codeigniter\\app\\Controllers\\User.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 15:08:11 --> Declaration of App\Controllers\User::create(App\Controllers\Reuqest $request) must be compatible with CodeIgniter\RESTful\ResourceController::create()
in APPPATH\Controllers\User.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 15:17:24 --> Declaration of App\Controllers\User::create(App\Controllers\Request $request) must be compatible with CodeIgniter\RESTful\ResourceController::create()
in APPPATH\Controllers\User.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 15:17:43 --> Undefined property: App\Controllers\User::$rquest
in APPPATH\Controllers\User.php on line 22.
 1 APPPATH\Controllers\User.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\User::$rquest', 'C:\\teste_api_codeigniter\\app\\Controllers\\User.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 15:17:56 --> Too few arguments to function App\Controllers\User::genericResponse(), 3 passed in C:\teste_api_codeigniter\app\Controllers\User.php on line 23 and exactly 4 expected
in APPPATH\Controllers\User.php on line 45.
 1 APPPATH\Controllers\User.php(23): App\Controllers\User->genericResponse(null, [...], 500)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 18:18:28 --> Declaration of App\Controllers\User::update($id) must be compatible with CodeIgniter\RESTful\ResourceController::update($id = null)
in APPPATH\Controllers\User.php on line 36.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-10-13 18:38:27 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ...ua Francisca da Cruz Macedo', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "users" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "users" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "users" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\User.php(49): CodeIgniter\Model->update('1', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\User->update('1')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-13 18:38:27 --> pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ...ua Francisca da Cruz Macedo', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" SET "name_or_fantasy" = :name_or_fantasy:, "cpf_cnpj" = :cpf_cnpj:, "address" = :address:, "type_user" = :type_user:, "updated_at" = :updated_at:
WHERE "users"."id" IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(49): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-13 18:40:26 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "users" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "users" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "users" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\User.php(49): CodeIgniter\Model->update('1', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\User->update('1')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-13 18:40:26 --> pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" SET "name_or_fantasy" = :name_or_fantasy:, "cpf_cnpj" = :cpf_cnpj:, "address" = :address:, "type_user" = :type_user:, "updated_at" = :updated_at:
WHERE "users"."id" IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(49): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-13 18:41:24 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "users" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "users" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "users" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\User.php(49): CodeIgniter\Model->update('1', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\User->update('1')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-13 18:41:24 --> pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" SET "name_or_fantasy" = :name_or_fantasy:, "cpf_cnpj" = :cpf_cnpj:, "address" = :address:, "type_user" = :type_user:, "updated_at" = :updated_at:
WHERE "users"."id" IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(49): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 18:42:03 --> Array to string conversion
in APPPATH\Controllers\User.php on line 39.
 1 APPPATH\Controllers\User.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\teste_api_codeigniter\\app\\Controllers\\User.php', 39)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-13 18:42:55 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "users" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "users" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "users" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\User.php(49): CodeIgniter\Model->update('1', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\User->update('1')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-13 18:42:55 --> pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" SET "name_or_fantasy" = :name_or_fantasy:, "cpf_cnpj" = :cpf_cnpj:, "address" = :address:, "type_user" = :type_user:, "updated_at" = :updated_at:
WHERE "users"."id" IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(49): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-13 18:46:12 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "users" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "users" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "users" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\User.php(49): CodeIgniter\Model->update('1', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\User->update('1')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-13 18:46:12 --> pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" SET "name_or_fantasy" = :name_or_fantasy:, "cpf_cnpj" = :cpf_cnpj:, "address" = :address:, "type_user" = :type_user:, "updated_at" = :updated_at:
WHERE "users"."id" IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(49): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-13 18:48:19 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "users" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "users" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "users" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\User.php(50): CodeIgniter\Model->update('1', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\User->update('1')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-13 18:48:19 --> pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" SET "name_or_fantasy" = :name_or_fantasy:, "cpf_cnpj" = :cpf_cnpj:, "address" = :address:, "type_user" = :type_user:, "updated_at" = :updated_at:
WHERE "users"."id" IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(50): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
ERROR - 2023-10-13 18:49:18 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^ in C:\teste_api_codeigniter\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\teste_api_co...', 187)
#1 C:\teste_api_codeigniter\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'UPDATE "users" ...')
#2 C:\teste_api_codeigniter\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "users" ...')
#3 C:\teste_api_codeigniter\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "users" ...')
#4 C:\teste_api_codeigniter\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" ...', Array, false)
#5 C:\teste_api_codeigniter\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#6 C:\teste_api_codeigniter\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\teste_api_codeigniter\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\teste_api_codeigniter\app\Controllers\User.php(50): CodeIgniter\Model->update('1', Array)
#9 C:\teste_api_codeigniter\system\CodeIgniter.php(919): App\Controllers\User->update('1')
#10 C:\teste_api_codeigniter\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\teste_api_codeigniter\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\teste_api_codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\teste_api_codeigniter\system\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_co...')
#14 {main}
CRITICAL - 2023-10-13 18:49:18 --> pg_query(): Query failed: ERROR:  column &quot;updated_at&quot; of relation &quot;users&quot; does not exist
LINE 1: ..., &quot;address&quot; = 'rua Francisc', &quot;type_user&quot; = 'PJ', &quot;updated_a...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE "users" SET "name_or_fantasy" = :name_or_fantasy:, "cpf_cnpj" = :cpf_cnpj:, "address" = :address:, "type_user" = :type_user:, "updated_at" = :updated_at:
WHERE "users"."id" IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(50): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->update('1')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 18:59:51 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::post()
in APPPATH\Controllers\User.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 19:00:40 --> Declaration of App\Controllers\User::create(App\Controllers\Request $request) must be compatible with CodeIgniter\RESTful\ResourceController::create()
in APPPATH\Controllers\User.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 19:00:54 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::post()
in APPPATH\Controllers\User.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 19:04:12 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::post()
in APPPATH\Controllers\User.php on line 27.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:17:31 --> Declaration of App\Controllers\User::create(CodeIgniter\HTTP\Request $request) must be compatible with CodeIgniter\RESTful\ResourceController::create()
in APPPATH\Controllers\User.php on line 19.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-13 23:20:41 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::post()
in APPPATH\Controllers\User.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:22:54 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::post()
in APPPATH\Controllers\User.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:26:05 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1724.
 1 SYSTEMPATH\BaseModel.php(1724): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(748): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\User.php(38): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:26:15 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1724.
 1 SYSTEMPATH\BaseModel.php(1724): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(748): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\User.php(38): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:27:29 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1724.
 1 SYSTEMPATH\BaseModel.php(1724): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(748): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\User.php(38): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:30:19 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1724.
 1 SYSTEMPATH\BaseModel.php(1724): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(748): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\User.php(38): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:30:51 --> Undefined variable $id
in APPPATH\Controllers\User.php on line 39.
 1 APPPATH\Controllers\User.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $id', 'C:\\teste_api_codeigniter\\app\\Controllers\\User.php', 39)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
CRITICAL - 2023-10-13 23:36:30 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::post()
in APPPATH\Controllers\User.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->create()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\teste_api_codeigniter\\public\\index.php')
